apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toolpod
  name: toolpod
spec:
  containers:
  - image: #informe seu repo de imagens
    name: toolpod
    command: [ "sleep", "infinity" ]
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "32Mi"
        cpu: "100m"
